FOOD_WARNINGS = {
    'Diabetes': [
        ('White Rice', 'Spikes blood sugar rapidly due to high glycemic index'),
        ('White Bread', 'Refined carbs break down into sugar quickly'),
        ('Sugary Drinks', 'Loaded with sugar causing immediate glucose spike'),
        ('Candy & Sweets', 'Pure sugar with zero nutritional value'),
        ('Fruit Juice', 'Concentrated sugar without fiber from whole fruit'),
        ('Pastries & Cakes', 'Combination of refined flour and sugar'),
        ('Potatoes', 'High starch content raises blood sugar'),
        ('Breakfast Cereals', 'Most are heavily sweetened with added sugar'),
    ],
    'Hypertension': [
        ('Table Salt', 'Excess sodium directly raises blood pressure'),
        ('Pickles & Papad', 'Very high sodium content from brining'),
        ('Processed Meats', 'Bacon, sausage, salami loaded with sodium'),
        ('Canned Soups', 'Often contain 500-900mg sodium per serving'),
        ('Chips & Namkeen', 'High sodium and unhealthy fats'),
        ('Fast Food', 'Single meal can exceed daily sodium limit'),
        ('Soy Sauce', 'Extremely high sodium content'),
        ('Frozen Meals', 'Packed with sodium as preservative'),
    ],
    'Heart Disease': [
        ('Fried Foods', 'Trans fats and saturated fats clog arteries'),
        ('Full-Fat Dairy', 'Butter, cream, cheese raise LDL cholesterol'),
        ('Red Meat', 'High saturated fat, raises heart risk'),
        ('Butter & Ghee', 'Saturated fats increase bad cholesterol'),
        ('Trans Fats', 'Hydrogenated oils are worst for heart health'),
        ('Alcohol', 'Weakens heart muscle and raises BP'),
        ('Processed Snacks', 'Contain trans fats and excess sodium'),
        ('Cream-Based Sauces', 'Heavy cream raises cholesterol levels'),
    ],
    'Obesity': [
        ('Sugary Snacks', 'Empty calories that promote fat storage'),
        ('Soda & Soft Drinks', 'Liquid calories with no satiety signal'),
        ('Fast Food', 'Calorie-dense with poor nutritional quality'),
        ('Ice Cream', 'High sugar and high fat combination'),
        ('Refined Carbs', 'White flour products cause overeating'),
        ('Large Portions', 'Excess calories regardless of food type'),
        ('Pizza', 'Calorie-dense with cheese and refined crust'),
        ('Milkshakes', 'Can contain 500-1000 calories per serving'),
    ],
    'None': []
}

HEALTHY_ALTERNATIVES = {
    'White Rice': 'Brown Rice / Cauliflower Rice / Quinoa',
    'White Bread': 'Whole Wheat Bread / Multigrain Bread / Oats Roti',
    'Sugary Drinks': 'Water / Green Tea / Lemon Water / Coconut Water',
    'Candy & Sweets': 'Fresh Berries / Dark Chocolate (70%+) / Dates',
    'Fruit Juice': 'Whole Fresh Fruit / Vegetable Juice (no sugar)',
    'Pastries & Cakes': 'Oat Muffins / Fruit Salad / Greek Yogurt with Honey',
    'Potatoes': 'Sweet Potato / Cauliflower Mash / Turnips',
    'Breakfast Cereals': 'Oatmeal / Muesli / Homemade Granola',
    'Table Salt': 'Herbs & Spices / Rock Salt (limited) / Lemon Juice',
    'Pickles & Papad': 'Fresh Salad / Roasted Vegetables / Cucumber Sticks',
    'Processed Meats': 'Grilled Chicken / Fresh Fish / Tofu / Lentils',
    'Canned Soups': 'Homemade Soup / Dal / Clear Vegetable Broth',
    'Chips & Namkeen': 'Roasted Chickpeas / Rice Cakes / Makhana',
    'Fast Food': 'Home-Cooked Meals / Salad Bowls / Grilled Wraps',
    'Soy Sauce': 'Coconut Aminos / Low-Sodium Soy Sauce / Lemon Herb Dressing',
    'Frozen Meals': 'Fresh Cooked Meals / Meal Prep Containers / Salads',
    'Fried Foods': 'Baked / Grilled / Air-Fried / Steamed versions',
    'Full-Fat Dairy': 'Low-Fat Yogurt / Almond Milk / Skimmed Milk / Oat Milk',
    'Red Meat': 'Grilled Chicken / Fish / Lentils / Tofu / Turkey',
    'Butter & Ghee': 'Olive Oil / Avocado Oil / Nut Butter (unsweetened)',
    'Trans Fats': 'Healthy Oils (olive, coconut) / Natural Fat Sources',
    'Alcohol': 'Sparkling Water / Herbal Tea / Fruit-Infused Water',
    'Processed Snacks': 'Mixed Nuts / Roasted Seeds / Fresh Fruit',
    'Cream-Based Sauces': 'Tomato-Based Sauce / Olive Oil Dressing / Pesto',
    'Sugary Snacks': 'Trail Mix / Roasted Makhana / Fruit with Nut Butter',
    'Soda & Soft Drinks': 'Sparkling Water / Buttermilk / Jaljeera',
    'Ice Cream': 'Frozen Banana / Greek Yogurt / Sorbet (no sugar)',
    'Refined Carbs': 'Whole Grains / Millets / Sweet Potato / Oats',
    'Large Portions': 'Smaller Plates / Mindful Eating / 4-5 Small Meals',
    'Pizza': 'Whole Wheat Base Pizza / Salad Bowl / Wraps',
    'Milkshakes': 'Smoothie with Fruit & Yogurt / Protein Shake',
}

ALLERGY_REPLACEMENTS = {
    'Nut Allergy': {
        'Almonds': 'Sunflower Seeds',
        'Peanut Butter': 'Sunflower Seed Butter',
        'Walnuts': 'Pumpkin Seeds',
        'Cashews': 'Roasted Chickpeas',
        'Mixed Nuts': 'Roasted Seeds Mix',
        'nuts': 'seeds',
    },
    'Gluten Intolerance': {
        'Wheat Bread': 'Rice Bread / Corn Tortilla',
        'Regular Pasta': 'Rice Pasta / Zucchini Noodles',
        'Roti': 'Rice Flour Roti / Jowar Roti',
        'Oats': 'Gluten-Free Oats / Quinoa Flakes',
        'Barley': 'Millet / Rice',
        'Whole Wheat': 'Rice Flour / Buckwheat Flour',
    },
    'Lactose Intolerance': {
        'Milk': 'Almond Milk / Oat Milk / Soy Milk',
        'Cheese': 'Vegan Cheese / Nutritional Yeast',
        'Yogurt': 'Coconut Yogurt / Almond Milk Yogurt',
        'Curd': 'Coconut Curd / Soy Curd',
        'Paneer': 'Tofu / Tempeh',
        'Butter': 'Olive Oil / Coconut Oil',
        'Cream': 'Coconut Cream / Cashew Cream',
    }
}